export const wordBank = [
  "apple", "artist", "angle", "answer", "animal", "agent", "action", "afford", "assist", "armor", 
  "allow", "attire", "alike", "aspect", "album", "author", "agree", "accord", "aspire", "active", 
  "beauty", "barrel", "brave", "bridge", "bottle", "beacon", "baffle", "button", "belief", "better", 
  "borrow", "bright", "behave", "build", "bubble", "butter", "banquet", "bundle", "border", "beyond", 
  "camera", "castle", "carbon", "candle", "clever", "credit", "copper", "cookie", "cherry", "column", 
  "combat", "course", "custom", "circle", "create", "casual", "chorus", "cushion", "cotton", "cruise", 
  "cactus", "coffee", "cancel", "closet", "corner", "cousin", "desert", "damage", "danger", "dollar", 
  "defend", "demand", "device", "delight", "depend", "digest", "dragon", "detail", "domain", "divide", 
  "delete", "distant", "diamond", "double", "design", "decay", "donut", "diesel", "dinner", "decide", 
  "energy", "excuse", "effect", "effort", "empire", "export", "employ", "evolve", "expand", "expert", 
  "emerald", "enlarge", "engine", "extreme", "extinct", "factory", "fortune", "freedom", "feather", 
  "fiction", "forward", "flower", "founder", "fitness", "fashion", "feature", "fragile", "fossil", 
  "friction", "farmer", "forest", "furnish", "funeral", "freight", "gesture", "garage", "gadget", 
  "gentle", "gather", "garden", "granite", "graphic", "golden", "graceful", "gravel", "gravity", 
  "general", "govern", "holiday", "harvest", "hazard", "hamster", "humble", "horizon", "heading", 
  "habitat", "highway", "history", "hungry", "harmony", "healthy", "hundred", "housing", "impress", 
  "infant", "income", "instant", "inquire", "inspire", "imagine", "install", "initial", "improve", 
  "involve", "insist", "instead", "inherit", "invade", "journey", "justice", "journal", "justify", 
  "jealous", "jigsaw", "jackpot", "jungle", "knuckle", "kingdom", "kitchen", "kindly", "kinetic", 
  "knowing", "knotty", "kitten", "lantern", "limited", "lasting", "leather", "lighter", "leading", 
  "liberty", "loyalty", "logical", "laptop", "linger", "lattice", "learned", "laundry", "letters", 
  "monster", "machine", "mystery", "mission", "mentor", "maiden", "magnet", "motive", "method", 
  "melody", "mineral", "measure", "maximum", "minimum", "monitor", "natural", "noble", "nectar", 
  "neutral", "nervous", "nurture", "network", "nominal", "numeric", "octagon", "optic", "observe", 
  "organic", "orchard", "overlap", "outline", "obscure", "optical", "outcome", "outside", "octopus", 
  "package", "paradise", "pumpkin", "pattern", "plastic", "picture", "purpose", "perfect", "protect", 
  "pathway", "pretend", "passage", "partner", "peaceful", "patience", "partial", "quality", "quartz", 
  "quarter", "qualify", "quiet", "quick", "quote", "quest", "quaint", "radiant", "request", "rebuild", 
  "recess", "recover", "refresh", "replay", "reflect", "reject", "rewind", "reserve", "resolve", 
  "recycle", "scholar", "service", "season", "storage", "science", "shelter", "student", "static", 
  "startup", "segment", "sunset", "speaker", "success", "certain", "silence", "suspend", "sunrise", 
  "tractor", "traffic", "trigger", "trophy", "temple", "theater", "texture", "training", "trample", 
  "transit", "thunder", "triumph", "trusted", "teacher", "trouble", "upstage", "upright", "upgrade", 
  "unfold", "unique", "uniform", "unreal", "utility", "useful", "upkeep", "unusual", "urgent", 
  "victory", "variety", "vehicle", "venture", "verdict", "village", "virtual", "voyage", "vintage", 
  "version", "visible", "visitor", "voltage", "vanilla", "valiant", "wisdom", "welcome", "walnut", 
  "waiting", "willing", "welfare", "workout", "warmth", "winner", "writing", "workshop", "witness", 
  "window", "wonder", "youthful", "yogurt", "yellow", "zephyr", "zipper", "zestful", "zenith", "zebra", 
  "zigzag", "zealous", "zodiac", "zonked"
];
